version: '3.8'
services:
  it_project_2021:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44343:80" # Map container port 80 to host port 8080
    depends_on:
      - sql_server
    networks:
      - it_project_network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql_server,1433;Database=aspnet-IT_project_2021;User Id=sa;Password=dbpassword;

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433" # Map SQL Server port 1433
    environment:
      SA_PASSWORD: "dbpassword"
      ACCEPT_EULA: "Y"
    networks:
      - it_project_network
    volumes:
      - sql_data:/var/opt/mssql

networks:
  it_project_network:
    driver: bridge

volumes:
  sql_data:
