## Deployment for application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app
  namespace: gym-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
      - name: gym-app
        image: ${{ secrets.DOCKERHUB_USERNAME }}/gym-membership-app:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
